app_axe:
    resource: "@AppBundle/Controller/AxeController.php"
    type:     annotation

app_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_editeur:
    resource: "@AppBundle/Controller/Editeur"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"